// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/11/2026, 5:10:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/xun-xia/Development/tracer/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/plugins/**/*.{js,ts,mjs}","/Users/xun-xia/Development/tracer/composables/**/*.{js,ts,mjs}","/Users/xun-xia/Development/tracer/utils/**/*.{js,ts,mjs}","/Users/xun-xia/Development/tracer/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/xun-xia/Development/tracer/app.config.{js,ts,mjs}","/Users/xun-xia/Development/tracer/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;