create table if not exists public.feedback_submissions (
    id bigint generated by default as identity primary key,
    feedback_type text not null check (feedback_type in ('problem', 'feature')),
    severity smallint,
    message text not null check (char_length(message) between 3 and 4000),
    language text not null default 'en' check (char_length(language) between 2 and 16),
    source_path text not null default '/feedback' check (char_length(source_path) <= 200),
    submitted_by uuid references auth.users(id) on delete set null default auth.uid(),
    status text not null default 'new' check (status in ('new', 'reviewing', 'planned', 'resolved', 'closed')),
    created_at timestamptz not null default now(),
    constraint feedback_severity_matches_type check (
        (feedback_type = 'problem' and severity between 1 and 5)
        or (feedback_type = 'feature' and severity is null)
    )
);

alter table public.feedback_submissions enable row level security;

revoke all on table public.feedback_submissions from anon, authenticated;
grant insert on table public.feedback_submissions to anon, authenticated;
grant usage, select on sequence public.feedback_submissions_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit feedback" on public.feedback_submissions;
create policy "Anyone can submit feedback"
on public.feedback_submissions
for insert
to anon, authenticated
with check (submitted_by is null or submitted_by = auth.uid());

create index if not exists feedback_submissions_status_created_at_idx
on public.feedback_submissions (status, created_at desc);

comment on table public.feedback_submissions is
    'Problem reports and feature requests submitted from the Tracer website.';
